fix(#296): get available balances from custom hooks
darwinia-network/legacy-apps pull request #298
Opened 2021-11-22 06:39 UTC by chunqiuyiyu

2021-11-22 06:55 UTC, WoeOm commented
#296 bug 是 types 引起的

2021-11-22 06:55 UTC, WoeOm requested changes

2021-11-22 06:55 UTC, WoeOm commented on packages/react-query/src/Balance.tsx
> +  const [value] = useDarwiniaAvailableBalances(params as string);
Balance.tsx 需要显示的是 可转账 + 锁定  的数额。

Available.tsx 表示 可转账 数额

2021-11-22 07:05 UTC, chunqiuyiyu commented
> #296 bug 是 types 引起的

意思是解决这个问题不需要更换数据的获取方式，更新 types 就可以了吗？

2021-11-22 07:54 UTC, WoeOm commented
> > #296 bug 是 types 引起的
> 
> 意思是解决这个问题不需要修改数据的获取方式，更新 types 就可以了吗？

看 issue 截图，大概率是这个问题。 @sxlwar pangoro balance 相关 types 是否有修改

2021-11-22 08:29 UTC, sxlwar commented
> 看 issue 截图，大概率是这个问题。 @sxlwar pangoro balance 相关 types 是否有修改

没改过，和 pangolin 是一样的

2021-11-22 09:02 UTC, WoeOm commented
```
{
  "AccountInfo": "AccountInfoWithTripleRefCount"
}
```
少了这个类型
@sxlwar evolution.js 中，pangoro 的 specVersion 和 crab 是同一个文件，可能没生效

2021-12-14 02:23 UTC, HackFisher commented
@chunqiuyiyu Is this fixed? Can we close this?

@sxlwar Please help review this.

2021-12-14 02:25 UTC, chunqiuyiyu commented
> @chunqiuyiyu Is this fixed? Can we close this?
> 
> @sxlwar Please help review this.

This PR is incorrect, I will close it,

2021-12-14 02:25 UTC, closed without merging